apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    k8s-app: fluentd
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: logging
  name: fluentd-wf-logging
  namespace: wavefront