apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: wavefront
    app.kubernetes.io.instance: "hyperlogs"
    app.kubernetes.io/component: logging
    app: hyperlogs-proxy
  name: hyperlogs-proxy
  namespace: wavefront
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: wavefront
      app.kubernetes.io/component: logging
      app: hyperlogs-proxy
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/name: wavefront
        app.kubernetes.io/component: logging
        app: hyperlogs-proxy
    spec:
      securityContext:
        runAsNonRoot: true
        runAsUser: 1000
        runAsGroup: 2000
      containers:
      - env:
        - name: WAVEFRONT_URL
          value: https://springlogs.wavefront.com/api
        - name: WAVEFRONT_TOKEN
          value: 847510b2-df9f-49bd-9a3e-9ec801a55f07
        - name: WAVEFRONT_PROXY_ARGS
          value: --customMessageTags log
        image: wavefronthq/proxy:11.3
        imagePullPolicy: IfNotPresent
        name: proxy
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        securityContext:
          allowPrivilegeEscalation: false
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      terminationGracePeriodSeconds: 30
