apiVersion: v1
kind: Service
metadata:
  labels:
    app: hyperlogs-proxy
    app.kubernetes.io/name: wavefront
    app.kubernetes.io/component: logging
  name: hyperlogs-proxy
  namespace: wavefront
spec:
  ports:
  - port: 2878
    protocol: TCP
    targetPort: 2878
  selector:
    app: hyperlogs-proxy
  sessionAffinity: None
status:
  loadBalancer: {}
